# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - gem install slather --no-ri --no-rdoc
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/ObjC-KFStdLib.xcworkspace -scheme ObjC-KFStdLib-Example -destination 'platform=iOS Simulator,name=iPhone 6' -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
after_success:
  - bundle exec slather

